#167128050 user login
katunold/ekalaamu pull request #13
Opened 2019-10-02 08:44 UTC by m-asiimwe

#### What does this PR do?
- add user login UI and implementation
- add links to landing page and signup form
- refactor folder structure
#### Description of Task to be completed?
- allow users to login into ekalaamu if they're registered
#### How should this be manually tested?
1. clone this repo and check into the branch `ft-user-login-167128050` 
2. start the server `npm start` 
3. navigate to the route `auth/login`

2019-10-02 18:26 UTC, kdaglas requested changes

2019-10-02 18:26 UTC, kdaglas commented on src/styles.scss
> +}
new line needed here... hahahaha

2019-10-02 18:26 UTC, kdaglas commented on src/app/shared/interceptors/error/error-interceptor.service.ts
> +import { environment } from '../../../../environments/environment';
did we stick to absolute or we continued with these ones...

2019-10-02 18:46 UTC, kdaglas commented
@m-asiimwe I suggest you use the CSS for the signup page so that you maintain the look and feel of the forms and all the elements that you have added... and besides it will reduce rewriting CSS... if you need help, just tap your homeboy

2019-10-07 10:11 UTC, katunold requested changes
Hey @m-asiimwe, I have failed to navigate the login page while using the deployment preview.

2019-10-07 10:11 UTC, katunold commented on package.json
> +    "@angular/router": "~8.1.3",
I hope these upgrades are not  causing the app to break

2019-10-07 10:11 UTC, katunold commented on src/app/app.module.ts
> +  providers: [LoginService, ToasterService,
@m-asiimwe I don't this was necessary because it's a deprecated way of registering services, you can just add this `
@Injectable({
	providedIn: 'root'
})
`
in just before you define the service class

2019-10-07 10:11 UTC, katunold commented on src/app/components/login/login.component.html
> +        <!--emailCtrl.errors?.required-->
@m-asiimwe you may need to do away with the commented code, probably you forgot

2019-10-07 10:11 UTC, katunold commented on src/app/components/login/login.component.spec.ts
> +  // });
Delete commented code please

2019-10-07 10:11 UTC, katunold commented on src/app/components/landing-page/landing.component.html
> +        <p class="login-button"><a href="/auth/login">Log in</a></p>
@m-asiimwe don't you think you are supposed to Angular's routerLink instead of href attribute

2019-10-07 10:11 UTC, katunold commented on src/app/auth/components/login/login.component.spec.ts
> +
Commented code again, kindly do away with commented code in case you don't see it's importance in the future

2019-10-21 10:13 UTC, m-asiimwe commented on src/app/components/landing-page/landing.component.html
> +        <p class="login-button"><a href="/auth/login">Log in</a></p>
oh.. thanks

2019-10-30 01:55 UTC, merged